### ISSUE TITLE
RSS를 지원하실 생각은 없으신가요?

### ISSUE THREAD

**Issue by benjioh5** [zerobased-co/muchtrans#14]
RSS 구독을 하려고 보니 지원이 안 되서 이렇게 이슈 남깁니다!

**Comment by lqez** [comment]
지원되면 좋을 것 같습니다. 좋은 의견 감사합니다.

**Comment by lqez** [comment]
@benjioh5 감사합니다. RSS 피드 지원을 추가했습니다. 한국어 링크는 다음과 같습니다.
<https://muchtrans.com/feeds/ko.xml>

**Comment by benjioh5** [comment]
감사합니다!
