### ISSUE TITLE
ACTION REQUIRED: Relicense of translated articles

### ISSUE THREAD

**Issue by lqez** [zerobased-co/muchtrans#38]
Thank you all translators! We are planning to relicense translated articles.
Till now, We've published these articles under MIT license as same as `muchtrans.com` code itself.

I would like to change it to [`CC-BY-SA`](https://creativecommons.org/licenses/by-sa/4.0/) – is a proper license than MIT, at least for documents. Since muchtrans.com has contributors, we have to get permissions from people who contributed. Please leave a comment like below in this issue thread.

```
I, <your-name-here>, give permission to license my contributions to muchtrans.com
under CC-BY-SA. I've used the email address <your-email-here>.
```

## When will this change applied
We hope to change licenses of translated documents and set a new default license policy from June 1, 2019.

## What if the original content restricts the license of the translated article
We apply CC-BY-SA as a default license, not restrict at all. Each translated article can have a different license by its original content. In this case, we will put proper information as headers at the top of each markdown file and they will be displayed in rendered HTML.

## What if I don't agree
We think this should be a better choice not only for translators but also for authors of original articles.
For people who do not respond to this issue, we will assume that as an agreement in most cases. But if you can't agree with relicensing, please leave a comment with objection. We will try to keep your opinion as much as possible.

## How the license of translated articles is effective
I'm sorry, we're not lawyers. But we understand the importance of document licensing and will try to keep the copyright of authors and translators.

**Comment by lqez** [comment]
The following people are contributors of translations on muchtrans.com (no order)
@dahlia 
@Jiwoong 
@bakyeono 
@darjeeling 
@sungbinlim 
@easylogic 
@corazzon 
@Bloodevil

**Comment by corazzon** [comment]
I, < corazzon >, give permission to license my contributions to muchtrans.com
under CC-BY-SA. I've used the email address <joeunpark@gmail.com>.

**Comment by Jiwoong** [comment]
I, Jiwoong, give permission to license my contributions to muchtrans.com
under CC-BY-SA. I've used the email address jiwoong.heo@gmail.com.

**Comment by Bloodevil** [comment]
I, Bloodevil, give permission to license my contributions to muchtrans.com
under CC-BY-SA. I've used the email address bloodevil4@gmail.com.

**Comment by darjeeling** [comment]
I, Bae KwonHan , give permission to license my contributions to muchtrans.com
under CC-BY-SA. I've used the email address <darjeeling@gmail.com>.
Thanks for your effort

**Comment by dahlia** [comment]
I, Hong Minhee, give permission to license my contributions to <muchtrans.com> under CC-BY-SA. I've used the email address <hong.minhee@gmail.com>.

**Comment by lqez** [comment]
Thank you all contributors. I'm closing this and preparing to relicense now.
