### ISSUE TITLE
Support watch mode

### ISSUE THREAD

**Issue by adhrinae** [zerobased-co/muchtrans#44]
In development environment, it is quite uncomfortable to run `build.py` script everytime I modify template files. 

So I tried [this package](https://github.com/samuelcolvin/watchgod/) locally, however I couldn't implement this functionality because of the lack of knowledge in Python ecosystem.

What I imagined are
* Watching files in `articles`, `templates` directories only.
* Exclude `_build` folder from watching
* (Optional) Run web server watch mode enabled in a one script execution.

**Comment by lqez** [comment]
I've used `python3 -m http.server` or other simple services(like [shs](https://github.com/lqez/shs)) to test.
But it must be very useful if we can provide it. Nice idea.

**Comment by lqez** [comment]
I made a minimal setup for the dev server. At least now we can start a dev journey here.
