### ISSUE TITLE
번역 수정이 필요해보입니다

### ISSUE THREAD

**Issue by sungbinlim** [zerobased-co/muchtrans#6]
- 요약
[개발자에서 개발팀장이 되기까지 겪은 다섯가지 큰 실수](https://muchtrans.com/translations/techie-tech-lead-my-5-biggest-mistakes.ko.html) 글에서 4번 항목의 제목이 수정이 필요합니다.

4: 권한을 주기 위해 필요한 모든 것을 알고 제어하려고 했다
(원문) I wanted to know, and control, everything when I needed to empower others

제안: 다른 사람에게 위임해야 할 때 모든 것을 알고 제어하려고 했다.
이유: `I needed to empower others` 에서 `needed to ~` 는 `~ 했어야 했다` 로 번역합니다. 그래서 원문의 문장은 "나는 다른 사람에게 권한을 줬어야 했다" 로 해석해야 합니다. 그리고 앞에 `when` 이 붙었기 때문에 "다른 사람에게 권한을 줬어야 할 때" 로 번역이 되어야 합니다.

**Comment by lqez** [comment]
의견 감사합니다.
아직 사이트에서 바로 번역을 수정/제안 하는 기능이 없으므로, Git 또는 GitHub의 시스템을 통해서 수정을 진행하고 있습니다.

이 리포지터리를 fork 하신 후에 https://github.com/zerobased-co/muchtrans/blob/master/articles/techie-tech-lead-my-5-biggest-mistakes.ko.md 파일을 수정하고 커밋하셔서 Pull request를 만들어주시면 감사드리겠습니다.

**Comment by lqez** [comment]
Closed by #7
